/// <reference types="react" />
import { IAttachment, IContact } from '../types';
export declare const messageStatusIcon: (messageStatus: string, messageStatusDisplayingType: string, iconColor?: string | undefined, readIconColor?: string | undefined) => JSX.Element;
export declare const isAlphanumeric: (str: string) => boolean;
export declare const urlRegex: RegExp;
export declare const bytesToSize: (bytes: number, decimals?: number) => string;
export declare const systemMessageUserName: (contact: IContact, userId: string) => string;
export declare const downloadFile: (attachment: IAttachment) => Promise<void>;
export declare const calculateRenderedImageWidth: (width: number, height: number, maxWidth?: number | undefined, maxHeight?: number | undefined) => number[];
export declare const userLastActiveDateFormat: (date: Date) => string;
export declare const checkArraysEqual: (arr1: any[], arr2: any[]) => boolean;
export declare const getMetadataFromUrl: (url: string) => Promise<any>;
export declare const formatAudioVideoTime: (duration: number, currentTime: number) => string;
export declare const formatLargeText: (text: string, maxLength: number) => any;
export declare const getCaretPosition: (element: any) => number;
export declare const setCursorPosition: (element: any, position: number) => void;
export declare const placeCaretAtEnd: (el: any) => void;
export declare const detectOS: () => string | null;
export declare const detectBrowser: () => string | undefined;
export declare const getEmojisCategoryTitle: (categoryKey: string) => string;
