export declare const colors: {
    white: string;
    black: string;
    dark: string;
    blue: string;
    backgroundColor: string;
    darkModeBackgroundColor: string;
    darkModeSecondaryBackgroundColor: string;
    lightModeBackgroundColor: string;
    hoverBackgroundColor: string;
    darkModeHoverBackgroundColor: string;
    lightModeHoverBackgroundColor: string;
    textColor1: string;
    darkModeTextColor1: string;
    lightModeTextColor1: string;
    textColor2: string;
    textColor3: string;
    gray0: string;
    gray1: string;
    borderColor: string;
    primary: string;
    primaryLight: string;
    darkModePrimary: string;
    lightModePrimary: string;
    darkModePrimaryLight: string;
    lightModePrimaryLight: string;
    red1: string;
    red2: string;
    purple: string;
    defaultAvatarBackground: string;
    deleteUserIconBackground: string;
};
export declare const size: {
    mobileS: string;
    mobileM: string;
    mobileL: string;
    tablet: string;
    laptop: string;
    laptopL: string;
    max: string;
};
export declare const device: {
    mobileS: string;
    mobileM: string;
    mobileL: string;
    tablet: string;
    laptop: string;
    laptopL: string;
    max: string;
};
