/// <reference types="react" />
import { IAttachment, IChannel, IMessage } from '../../types';
interface IMessageProps {
    message: IMessage;
    channel: IChannel;
    isPendingMessage?: boolean;
    prevMessage?: IMessage;
    nextMessage: IMessage;
    stopScrolling: (stop: boolean) => void;
    setLastVisibleMessageId: (msgId: string) => void;
    handleScrollToRepliedMessage?: (msgId: string) => void;
    handleMediaItemClick?: (attachment: IAttachment) => void;
    isUnreadMessage: boolean;
    isThreadMessage: boolean;
    fontFamily?: string;
    ownMessageOnRightSide?: boolean;
    messageWidthPercent?: string | number;
    showSenderNameOnDirectChannel?: boolean;
    showSenderNameOnOwnMessages?: boolean;
    messageStatusAndTimePosition?: 'bottomOfMessage' | 'onMessage';
    messageStatusDisplayingType?: 'ticks' | 'text';
    ownMessageBackground?: string;
    incomingMessageBackground?: string;
    showOwnAvatar?: boolean;
    showMessageStatus?: boolean;
    showMessageTime?: boolean;
    showMessageStatusForEachMessage?: boolean;
    showMessageTimeForEachMessage?: boolean;
    hoverBackground?: boolean;
    messageReaction?: boolean;
    editMessage?: boolean;
    copyMessage?: boolean;
    replyMessage?: boolean;
    replyMessageInThread?: boolean;
    forwardMessage?: boolean;
    deleteMessage?: boolean;
    allowEditDeleteIncomingMessage?: boolean;
    reportMessage?: boolean;
    reactionIcon?: JSX.Element;
    editIcon?: JSX.Element;
    copyIcon?: JSX.Element;
    replyIcon?: JSX.Element;
    replyInThreadIcon?: JSX.Element;
    forwardIcon?: JSX.Element;
    deleteIcon?: JSX.Element;
    starIcon?: JSX.Element;
    staredIcon?: JSX.Element;
    reportIcon?: JSX.Element;
    openFrequentlyUsedReactions?: boolean;
    separateEmojiCategoriesWithTitle?: boolean;
    emojisCategoryIconsPosition?: 'top' | 'bottom';
    emojisContainerBorderRadius?: string;
    reactionIconOrder?: number;
    editIconOrder?: number;
    copyIconOrder?: number;
    replyIconOrder?: number;
    replyInThreadIconOrder?: number;
    forwardIconOrder?: number;
    deleteIconOrder?: number;
    starIconOrder?: number;
    reportIconOrder?: number;
    reactionIconTooltipText?: string;
    editIconTooltipText?: string;
    copyIconTooltipText?: string;
    replyIconTooltipText?: string;
    replyInThreadIconTooltipText?: string;
    forwardIconTooltipText?: string;
    deleteIconTooltipText?: string;
    starIconTooltipText?: string;
    reportIconTooltipText?: string;
    messageActionIconsColor?: string;
    inlineReactionIcon?: JSX.Element;
    reactionsDisplayCount?: number;
    showEachReactionCount?: boolean;
    reactionItemBorder?: string;
    reactionItemBorderRadius?: string;
    reactionItemBackground?: string;
    reactionItemPadding?: string;
    reactionItemMargin?: string;
    reactionsFontSize?: string;
    reactionsContainerBoxShadow?: string;
    reactionsContainerBorder?: string;
    reactionsContainerBorderRadius?: string;
    reactionsContainerBackground?: string;
    reactionsContainerTopPosition?: string;
    reactionsContainerPadding?: string;
    fileAttachmentsBoxWidth?: number;
    fileAttachmentsBoxBackground?: string;
    fileAttachmentsBoxBorder?: string;
    fileAttachmentsTitleColor?: string;
    fileAttachmentsSizeColor?: string;
    fileAttachmentsIcon?: JSX.Element;
    imageAttachmentMaxWidth?: number;
    imageAttachmentMaxHeight?: number;
    videoAttachmentMaxWidth?: number;
    videoAttachmentMaxHeight?: number;
}
declare const Message: ({ message, channel, handleScrollToRepliedMessage, handleMediaItemClick, stopScrolling, prevMessage, nextMessage, setLastVisibleMessageId, isUnreadMessage, isThreadMessage, fontFamily, ownMessageOnRightSide, messageWidthPercent, showSenderNameOnDirectChannel, showSenderNameOnOwnMessages, messageStatusAndTimePosition, messageStatusDisplayingType, ownMessageBackground, incomingMessageBackground, showOwnAvatar, showMessageStatus, showMessageTime, showMessageStatusForEachMessage, showMessageTimeForEachMessage, hoverBackground, messageReaction, editMessage, copyMessage, replyMessage, replyMessageInThread, deleteMessage, allowEditDeleteIncomingMessage, forwardMessage, reportMessage, reactionIcon, editIcon, copyIcon, replyIcon, replyInThreadIcon, forwardIcon, deleteIcon, starIcon, staredIcon, reportIcon, reactionIconOrder, openFrequentlyUsedReactions, editIconOrder, copyIconOrder, replyIconOrder, replyInThreadIconOrder, forwardIconOrder, deleteIconOrder, starIconOrder, reportIconOrder, reactionIconTooltipText, editIconTooltipText, copyIconTooltipText, replyIconTooltipText, replyInThreadIconTooltipText, forwardIconTooltipText, deleteIconTooltipText, starIconTooltipText, reportIconTooltipText, messageActionIconsColor, fileAttachmentsIcon, reactionsDisplayCount, showEachReactionCount, reactionItemBorder, reactionItemBorderRadius, reactionItemBackground, reactionItemPadding, reactionItemMargin, reactionsFontSize, reactionsContainerBoxShadow, reactionsContainerBorder, reactionsContainerBorderRadius, reactionsContainerBackground, reactionsContainerPadding, reactionsContainerTopPosition, fileAttachmentsBoxWidth, fileAttachmentsBoxBorder, fileAttachmentsTitleColor, fileAttachmentsSizeColor, imageAttachmentMaxWidth, imageAttachmentMaxHeight, videoAttachmentMaxWidth, videoAttachmentMaxHeight, emojisCategoryIconsPosition, emojisContainerBorderRadius, separateEmojiCategoriesWithTitle }: IMessageProps) => JSX.Element;
export default Message;
export declare const MessageStatusAndTime: import("styled-components").StyledComponent<"div", any, {
    withAttachment?: boolean | undefined;
    fileAttachment?: boolean | undefined;
    hide?: boolean | undefined;
    isSelfMessage?: boolean | undefined;
    bottomMargin?: boolean | undefined;
    leftMargin?: boolean | undefined;
    rtlDirection?: boolean | undefined;
    bottomOfMessage?: boolean | undefined;
}, never>;
