import React, { FC } from 'react';
import { IMessage, IUser } from '../../types';
interface SendMessageProps {
    draggedAttachments?: boolean;
    handleAttachmentSelected?: (state: boolean) => void;
    handleSendMessage?: (message: IMessage, channelId: string) => Promise<IMessage>;
    inputCustomClassname?: string;
    disabled?: boolean;
    showAddEmojis?: boolean;
    AddEmojisIcon?: JSX.Element;
    emojiIcoOrder?: number;
    showAddAttachments?: boolean;
    AddAttachmentsIcon?: JSX.Element;
    attachmentIcoOrder?: number;
    sendIconOrder?: number;
    inputOrder?: number;
    CustomTypingIndicator?: FC<{
        from: IUser;
        typingState: boolean;
    }>;
    backgroundColor?: string;
    margin?: string;
    minHeight?: string;
    border?: string;
    borderRadius?: string;
    inputBorderRadius?: string;
    inputBackgroundColor?: string;
    inputPaddings?: string;
    selectedFileAttachmentsBoxBackground?: string;
    selectedFileAttachmentsBoxBorder?: string;
    selectedFileAttachmentsTitleColor?: string;
    selectedFileAttachmentsSizeColor?: string;
    selectedFileAttachmentsIcon?: JSX.Element;
    selectedAttachmentsBorderRadius?: string;
    replyMessageIcon?: JSX.Element;
    editMessageIcon?: JSX.Element;
    voiceMessage?: boolean;
    sendAttachmentSeparately?: boolean;
    allowMentionUser?: boolean;
    textSelectionBackgroundColor?: string;
}
declare const SendMessageInput: React.FC<SendMessageProps>;
export default SendMessageInput;
